Intel-bigdata/arrow

- cpp/src/jni/parquet/adapter.cc
Signed-off-by: Chendi Xue <chendi.xue@intel.com>
> [C++] Fix bugs when using offset to indicate rowGroupIndices

- cpp/src/arrow/CMakeLists.txt
- cpp/src/arrow/compute/kernels/probe.cc
- cpp/src/arrow/compute/kernels/probe.h
return an array of row idx if there are matches
based on quick hacks of isin kernel
> [C++] adding probe kernel

- cpp/src/arrow/compute/kernels/probe.cc
> [C++] cleanup probe kernel

- cpp/src/arrow/compute/kernels/sort_arrays_to_indices.cc
- cpp/src/arrow/compute/kernels/sort_arrays_to_indices_test.cc
sort_array_to_indices performance is acceptable for now
Signed-off-by: Chendi Xue <chendi.xue@intel.com>
> [C++] Change to use sort + merge

- cpp/src/arrow/CMakeLists.txt
- cpp/src/arrow/compute/kernels/ntake.cc
- cpp/src/arrow/compute/kernels/ntake.h
- cpp/src/arrow/compute/kernels/ntake_internal.h
based on quick hacks on Take kernel with skipping NULL indicies
TODO: should move this feature into TakeOptions
> [C++] WIP NTake kernel

- cpp/src/arrow/compute/kernels/ntake.cc
- cpp/src/arrow/compute/kernels/ntake_internal.h
> [C++] refine NTake kernel

- java/adapter/common/src/main/java/org/apache/arrow/adapter/common/AdaptorReferenceManager.java
- java/gandiva/src/main/java/org/apache/arrow/gandiva/expression/InNode.java
Signed-off-by: Chendi Xue <chendi.xue@intel.com>
> [Java] Fix some code style issue

- cpp/src/gandiva/precompiled/time.cc
> [C++][Gandiva] fix overflow on date32

- cpp/src/jni/dataset/CMakeLists.txt
- cpp/src/jni/dataset/jni_wrapper.cpp
- cpp/src/jni/dataset/proto/Types.proto
Also, Use Arrow defined libprotobuf in jni/dataset
> Namespace collision: types, renamed to arrow::dataset::types

- cpp/src/gandiva/function_registry_math_ops.cc
- cpp/src/gandiva/precompiled/extended_math_ops.cc
- cpp/src/gandiva/precompiled/types.h
> [C++][Gandiva] Adding abs function

- cpp/src/arrow/dataset/discovery.cc
- cpp/src/arrow/dataset/discovery.h
- cpp/src/arrow/dataset/file_base.cc
- cpp/src/arrow/dataset/file_base.h
- cpp/src/arrow/dataset/test_util.h
- cpp/src/jni/dataset/CMakeLists.txt
- cpp/src/jni/dataset/concurrent_map.h
- cpp/src/jni/dataset/jni_wrapper.cpp
- cpp/src/jni/orc/concurrent_map.h
> [C++] fix code style

- cpp/src/plasma/lib/java/org_apache_arrow_plasma_PlasmaClientJNI.cc
lost this method due to rebase.
> add jni metrics method

- cpp/src/plasma/CMakeLists.txt
modify cmakelist.txt, will install libplasma_java.so
> install libplasma_java.so

- cpp/src/gandiva/function_registry_arithmetic.cc
- cpp/src/gandiva/precompiled/arithmetic_ops.cc
> [C++]support castINT from date32

- cpp/src/gandiva/function_registry_arithmetic.cc
- cpp/src/gandiva/precompiled/arithmetic_ops.cc
> [C++][Gandiva] Support more types for Cast

- cpp/src/plasma/vmemcache_store.cc
fix bug "InitialPath is not correct"
> [POAE7-318] fix bug "InitialPath is not correct"

- cpp/src/arrow/io/hdfs_internal.cc
> [C++] add additional libhdfs3 lib dir

- cpp/src/parquet/encoding.cc
> Offset buffer can be pre-grown in Parquet ByteArray reader

- java/vector/src/main/java/org/apache/arrow/vector/VectorLoader.java
- java/vector/src/main/java/org/apache/arrow/vector/VectorSchemaRoot.java
- java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowReader.java
To enable shuffle compression.
> [Java] compression workaround

- cpp/src/arrow/dataset/file_parquet.cc
> [C++] allow to optionally disable dict encoding

- cpp/src/plasma/CMakeLists.txt
remove numa, vmemcache dependency for conda package.
> [POAE7-353]remove numa, vmemcache dependency

- cpp/src/gandiva/function_registry_arithmetic.cc
- cpp/src/gandiva/precompiled/arithmetic_ops.cc
Signed-off-by: Chendi Xue <chendi.xue@intel.com>
> [oap-native-sql] Add castInt(int8)

- cpp/src/gandiva/function_registry_arithmetic.cc
- cpp/src/gandiva/function_registry_hash.cc
- cpp/src/gandiva/precompiled/arithmetic_ops.cc
- cpp/src/gandiva/precompiled/hash.cc
- cpp/src/gandiva/precompiled/types.h
- cpp/src/gandiva/tests/hash_test.cc
Add new precompiled functions in gandiva to support spark_hash and isNaN
@zhouyuan @rongma1997
> [oap-native-sql] support spark_hash and isNaN in gandiva

- java/dataset/pom.xml
- java/gandiva/pom.xml
> bump protobuf version to 3.4.0

- cpp/src/gandiva/function_registry_math_ops.cc
- cpp/src/gandiva/precompiled/extended_math_ops.cc
- cpp/src/gandiva/precompiled/extended_math_ops_test.cc
- cpp/src/gandiva/precompiled/types.h
This reverts commit e551b63e54ae26c3ca261a6148d8555d7aaf8a24.
> Revert "[oap-native-sql] adding round support"
